var cubesThree = [
    {
        Name: "Dayan Guhong V3 Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "54mm",
        Weight: "77.3g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fdayanguhv3.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$11.95",
        Rating: "6/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/dayan-guhong-v3m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Dayan Guhong V4 Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "66.5g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fdayanguhv4.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$14.95",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/dayan-guhong-v4m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Dayan Tengyun M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55mm",
        Weight: "77.3g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fdayantengm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$25.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/dayan/products/dayan-tengyun-3x3x3-m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Dayan Tengyun Magnetic V2 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "83g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fdayantengmv2.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$31.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/dayan/products/dayan-tengyun-v2m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan 11 M Pro ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "63g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgan11.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$64.95",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-11m-pro-stickerless-black/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan 354 Magnetic V2 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "54mm",
        Weight: "77g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgan354v2.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$34.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-354-v2m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan 356 Air M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "68g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganairm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$33.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-356-air-m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan 356 Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "74g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$32.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-356m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan 356 Magnetic LITE ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "74g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganmlite.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$27.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Gan 356 RS ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "72g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganrs.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$16.95",
        Rating: "5/10",
        Link: "none",
    },
    {
        Name: "Gan 356 X Magnetic V2 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "80g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganxv2.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$39.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Gan 356 XS ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "68g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganxs.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$49.95",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-356-xs/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan Speed Cube (GSC) ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "57mm",
        Weight: "83g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgansc.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$20.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "Guoguan Yuexiao EDM ",
        Magnets: "Yes",
        Stickerless: "No",
        Size: "55.5mm",
        Weight: "72g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganedm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$24.95",
        Rating: "6/10",
        Link: "link",
    },
    {
        Name: "Mofang Jiaoshi Meilong Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "71.8g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmeilongmag.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$6.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/moyu/products/moyu-meilong-3x3x3-m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Monster Go Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "85g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmonsterm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$19.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/gan/products/monstergo-3x3x3-m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Monster Go Traditional ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "81g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmonstergot.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$11.95",
        Rating: "6/10",
        Link: "none",
    },
    {
        Name: "Moyu RS3M 2020 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "86g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmoyurs3m.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$8.95",
        Rating: "6/10",
        Link: "https://speedcubing.org/collections/moyu/products/moyu-rs3m-2020/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Moyu Weilong GTS2 ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "80.2g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgts2.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$19.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "Moyu Weilong GTS2 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "92g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgts2m.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$25.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Moyu Weilong GTS3 ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "84g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgts3.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$29.95",
        Rating: "5/10",
        Link: "none",
    },
    {
        Name: "Moyu Weilong GTS3M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "92g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgts3m.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$34.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/moyu/products/moyu-weilong-gts3m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Moyu Weilong WR ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "80g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fwr.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$29.95",
        Rating: "5/10",
        Link: "none",
    },
    {
        Name: "Moyu Weilong WR M 2020 ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55mm",
        Weight: "Unknown",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fwrm2020.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$34.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/moyu/products/moyu-weilong-wrm-2020/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Moyu Weilong WR M Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "90g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fwrmm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$38.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "MsCube MS3-V1 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "79g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmscubes.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$29.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "MsCube MS3-V1 M Enhanced ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "74g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmscubee.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$34.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Qiyi MS Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "57mm",
        Weight: "81.8g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fqiyimsm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$7.95",
        Rating: "7/10",
        Link: "link",
    },
    {
        Name: "Qiyi Thunderclap V3 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "89g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fthunderv3.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$9.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/qiyi/products/qiyi-ms-3x3x3/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Qiyi Valk 3 ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "82.3g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fvalk3.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$19.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "Qiyi Valk 3 Elite M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "76g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fvalkelite.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$44.95",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/qiyi/products/qiyi-valk-3-elite-m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Qiyi Valk 3 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "85g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fvalk3.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$24.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/qiyi/products/qiyi-valk-3m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Qiyi Valk 3 Power ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "87.4g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fvalkpower.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$24.95",
        Rating: "5/10",
        Link: "none",
    },
    {
        Name: "Qiyi Valk 3 Power M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "94.4g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fpowerm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$38.95",
        Rating: "6/10",
        Link: "none",
    },
    {
        Name: "Qiyi Wuwei M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55mm",
        Weight: "90g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fwuweim.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$14.95",
        Rating: "8/10",
        Link: "https://cdn.shopify.com/s/files/1/0276/0133/8446/products/Screenshot_from_2019-12-05_18-11-59_180x.png?v=1596383584/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "YJ MGC Elite Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "87g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmgcem.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$22.95",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "YJ MGC Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "85.8g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmgcm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$14.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "YJ Yulong V2 Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "88.9g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fyulongv2.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$7.95",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/yj/products/yj-yulong-v2m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "YJ Zhilong Mini Magnetic ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "50mm",
        Weight: "57.5g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fzhilongmini.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$7.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/yj/products/yj-zhilong-3x3x3/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Yuxin Kylin V2 M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "82.4g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fkylinv2.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$9.95",
        Rating: "7/10",
        Link: "none",
    },
    {
        Name: "Yuxin Little Magic ",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "71.8g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Flm.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$4.95",
        Rating: "6/10",
        Link: "https://speedcubing.org/collections/yuxin/products/yuxin-little-magic-3x3x3/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Yuxin Little Magic M ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55.5mm",
        Weight: "78g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Flittlemagic.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$7.95",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/yuxin/products/yuxin-little-magic-3x3x3-m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Moyu RS3M 2021 Maglev ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "92g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Frs3mlaglev.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$13.99",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/moyu-rs3m-2021-maglev/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Moyu Weilong WR M 2021 Maglev ",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "55mm",
        Weight: "84g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fwrmmaglev.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$29.99",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/moyu-weilong-wrm-2021-maglev/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan i3",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "88g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgani3.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$62.99",
        Rating: "9/10",
        Link: "none",
    },
    {
        Name: "Gan 12 Maglev",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "66g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganmaglev.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$77.99",
        Rating: "9/10",
        Link: "none",
    },
    {
        Name: "Gan 12 M Leap",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "61g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganmleap.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$66.99",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Gan Mini M Pro",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "53mm",
        Weight: "54g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganminim.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$54.99",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/gan-mini-m-pro/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Monster Go AI",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "81g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fmonsterai.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$27.99",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/monstergo-ai-3x3x3/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan 11 M Duo",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "60g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgan11duo.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$46.99",
        Rating: "7/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/gan-11m-duo/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan 11 M",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "56g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgan11blank.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$34.99",
        Rating: "6/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/gan-11-m/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Gan 11 Air",
        Magnets: "No",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "50g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fgan11air.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$23.99",
        Rating: "5/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/gan-11-air/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "Dayan Zhanchi Pro M",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "77g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fzhanchipro.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$34.99",
        Rating: "8/10",
        Link: "none",
    },
    {
        Name: "Gan 356 i Carry",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "77.5g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Fganicarry.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$36.99",
        Rating: "8/10",
        Link: "https://speedcubing.org/collections/gan/products/gan-356-i-carry/?sca_ref=1249093.DLjOmDm1Z6",
    },
    {
        Name: "X-Man Tornado V2 M",
        Magnets: "Yes",
        Stickerless: "Yes",
        Size: "56mm",
        Weight: "72g",
        Img: 'https://firebasestorage.googleapis.com/v0/b/speedtimer-2.appspot.com/o/cubeslist%2Ftornadov2.jpeg?alt=media&token=9363a151-55da-4ad0-85f6-c030920f3adastorageRef',
        Price: "$24.99",
        Rating: "9/10",
        Link: "https://speedcubing.org/collections/3x3x3/products/x-man-tornado-v2m/?sca_ref=1249093.DLjOmDm1Z6",
    },
];

window.cubesListThree = cubesThree;